name: gradient_elevated_button
description: Custom Flutter button with gradient background for visually appealing UI.
version: 1.1.0
homepage: https://github.com/ChegzDev/gradient_elevated_button
repository: https://github.com/ChegzDev/gradient_elevated_button
environment:
  sdk: ^3.6.0
  flutter: ">=3.16.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

