name: gradient_elevated_button
description: Custom Flutter button with gradient background for visually appealing UI.
version: 1.0.5
homepage: https://github.com/ChegzDev/gradient_elevated_button
repository: https://github.com/ChegzDev/gradient_elevated_button
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

